<div id="contentWindow">
    <div id="topController">
        <div class="titleWrapper">
            <a class="welcomeLogin" href="#popupWrapper">欢迎登录</a>
        </div>
        <div class="toggleWrapper">
            <a class="toggle" href="#">&#9932;</a>
        </div>
    </div>
    <div id="formBlock">
        <div id="formContentWrapper">
            <input id="account" type="text" name="account" placeholder="用户名或者邮箱" autocomplete="off"
                   autofocus="autofocus" spellcheck="false" autocapitalize="off" autocorrect="off"/>
            <br />
            <label id="labelAccount" for="account" class="error"></label>
            <br />
            <input id="psw" type="password" name="psw" placeholder="密码" autocomplete="false" spellcheck="false"
                   autocapitalize="off" autocorrect="off"/>
            <br />
            <label id="labelPsw" for="psw" class="error"></label>
            <br/>
            <button class="submit login">登录</button>
            <div class="loader"></div>
        </div>
    </div>
    <div id="bottomController">
        <div class="titleWrapper">
            <a id="toRegister" href="#popupWrapper">还没有帐号？马上注册！&#8594;</a>
        </div>
    </div>
</div>
</div>